### ISSUE TITLE
loadValuesAsynchronouslyForKeys

### ISSUE THREAD

**Issue by Tongziqi** [dangercheng/ShortMediaCache#3]
请问下 现在AVURLAsset 的 loadValuesAsynchronouslyForKeys: completionHandler:默认流式播放就是边下载边播放的把，
为何还要自定义ShortMediaResourceLoader呢？[asset.resourceLoader setDelegate:self queue:dispatch_get_main_queue()];
可不可以用loadValuesAsynchronouslyForKeys，然后等下载完毕后再进行缓存，这样就不用使用子线程中去通过NSURLSession来实现下载。

**Comment by jiangcanming** [comment]
> 请问下 现在AVURLAsset 的 loadValuesAsynchronouslyForKeys: completionHandler:默认流式播放就是边下载边播放的把，
> 为何还要自定义ShortMediaResourceLoader呢？[asset.resourceLoader setDelegate:self queue:dispatch_get_main_queue()];
> 可不可以用loadValuesAsynchronouslyForKeys，然后等下载完毕后再进行缓存，这样就不用使用子线程中去通过NSURLSession来实现下载。

具体如何实现的，有相关demo吗？

**Comment by Tongziqi** [comment]
已经解决
